
create table users (login VARCHAR(32),password VARCHAR(32),primary key(login));
create table userFiles (fileId INT GENERATED BY DEFAULT AS IDENTITY, userLogin varchar(32), fileName varchar(64), fileSize biginteger);
create table shared (userLogin VARCHAR(32), fileId INT);